/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LobsterAttackRouteImport } from './routes/lobster-attack'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as IndexRouteImport } from './routes/index'

const LobsterAttackRoute = LobsterAttackRouteImport.update({
  id: '/lobster-attack',
  path: '/lobster-attack',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concierge': typeof ConciergeRoute
  '/lobster-attack': typeof LobsterAttackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concierge': typeof ConciergeRoute
  '/lobster-attack': typeof LobsterAttackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concierge': typeof ConciergeRoute
  '/lobster-attack': typeof LobsterAttackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/concierge' | '/lobster-attack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/concierge' | '/lobster-attack'
  id: '__root__' | '/' | '/concierge' | '/lobster-attack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConciergeRoute: typeof ConciergeRoute
  LobsterAttackRoute: typeof LobsterAttackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lobster-attack': {
      id: '/lobster-attack'
      path: '/lobster-attack'
      fullPath: '/lobster-attack'
      preLoaderRoute: typeof LobsterAttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConciergeRoute: ConciergeRoute,
  LobsterAttackRoute: LobsterAttackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
